.gitignore, README.md, package.json
This adds hosted docs. You can see them at https://jamesplease.github.io/materialish
=> Host storybook on GitHub pages

.eslintrc, components/navigation/navigation.js, components/table/table.js, package.json
=> Add eslint; fix lint errors

.storybook/preview-head.html, components/button/button.css, components/checkbox/checkbox.css, components/chip/chip.css, components/dialog/dialog.css, components/menu/menu.css, components/navigation/navigation.css, components/ripple/ripple.css, components/switch/switch.css, components/table/table.css, stories/chip.stories.js
As part of #8 
Also resolves #15 
---
This begins the process of normalizing our variable usage. **It's not complete**, and is instead meant to serve as a reference point.
=> WIP: Update variable usage

src/ripple/ripple.css
I broke the ripple in #28 . This fixes it. I'm not publishing a new npm version due to #50 (the styles aren't even in the npm package atm)
=> Fix ripple styles

docs/readmes/button.md, src/button/button.css
=> Make font-family a variable

src/avatar/avatar.js, src/button/button.js, src/checkbox/checkbox.js, src/ripple/ripple.js, src/switch/switch.js
=> Add PropTypes to components

CHANGELOG.md, package.json, src/ripple/ripple.js
=> Fix ripple

.gitignore, build/generate-icons.js, docs/components.js, docs/examples/icons.js, docs/readmes/icons.md, docs/src/common/nav.js, docs/src/icons/index.js, docs/src/icons/usage.js, docs/static.config.js, package.json, src/avatar/avatar.js, src/button/button.js, src/checkbox/checkbox.js, src/switch/switch.js
=> Add Icons catalog; fix propTypes

docs/components.js, src/button/button.css
=> Remove background for disabled flat/stroked buttons

build/generate-icons.js, docs/src/icons/catalog.css, docs/src/icons/catalog.js
=> Icon categories

docs/readmes/spinner.md, package.json, src/spinner/spinner.js
=> Spinner size

CHANGELOG.md, docs/package.json, docs/readmes/spinner.md, package.json, src/checkbox/checkbox.css
=> Fixing checkbox size

docs/components.js, docs/examples/radio.js, docs/readmes/radio.md, docs/static.config.js, src/index.js, src/radio/radio.css, src/radio/radio.js, stories/radio.stories.js
As part of #64 
Todo:
Label storybook buggy display:
=> Add Radio button

CHANGELOG.md, docs/package.json, docs/readmes/input.md, package.json, src/input/input.js
=> Input nodeRef prop

.newt.yml, src/table/table.css, src/table/table.js
Changing the way the transitionend events gets cancelled after the first call
=> Changing the way the transitionend events gets cancelled

docs/components.js, docs/examples/input.js, docs/examples/table.js, docs/readmes/button.md, docs/readmes/checkbox.md, docs/readmes/switch.md, docs/src/components/buttons.js, docs/src/components/component-doc.js, docs/src/components/progress-indicators.js, docs/src/components/selection-controls.js, src/checkbox/checkbox.css, src/switch/switch.css
Resolves #175 
Resolves #165 
Resolves #163
Resolves #164 
Resolves #129
=> Some docs updates

docs/src/common/expandable-container.css, docs/src/common/expandable-container.js, docs/src/common/nav.css, docs/src/common/nav.js
=> Add collapsible nav items

docs/readmes/action-chip.md, docs/readmes/avatar.md, docs/readmes/button.md, docs/readmes/checkbox.md, docs/readmes/choice-chip.md, docs/readmes/dialog.md, docs/readmes/elevation.md, docs/readmes/field.md, docs/readmes/filter-chip.md, docs/readmes/icon-button.md, docs/readmes/inline-spinner.md, docs/readmes/input-chip.md, docs/readmes/input.md, docs/readmes/menu.md, docs/readmes/radio.md, docs/readmes/snackbar.md, docs/readmes/spinner.md, docs/readmes/switch.md, docs/readmes/table.md
=> Always encourage use of materialish.css in docs

docs/readmes/input.md, src/input/input.css
=> Several updates

docs/readmes/spinner.md, src/spinner/spinner.css, stories/field.stories.js, stories/spinner.stories.js
=> Add CSS variable to enable single-color spinners

.eslintrc, docs/src/common/expandable-container.css, docs/src/common/nav.js, src/expandable/expandable.css, src/expandable/expandable.js, src/index.js
=> Add Expandable component (internal for now)

docs/examples/menu.js, docs/readmes/menu.md, src/menu/menu.css, src/menu/menu.js, stories/menu.stories.js
=> Add Menu.Separator component

src/table/table.js
Resolves #150 
I ignored the expandable row due to #190
=> Add PropTypes to table

docs/package.json, docs/src/common/utils/react-over-animations.js, docs/src/icons/catalog.css, docs/src/icons/catalog.js, docs/src/vendor/doc-components/markdown/code-highlighter.js, docs/src/vendor/react-over/compute-position/clamp.js, docs/src/vendor/react-over/compute-position/compute-pixel-coordinates.js, docs/src/vendor/react-over/compute-position/coordinates-map.js, docs/src/vendor/react-over/compute-position/dimensions-overlap.js, docs/src/vendor/react-over/compute-position/get-default-origin-from-rotated-coordinates.js, docs/src/vendor/react-over/compute-position/get-first-resolution-axis-from-rotated-coordinates.js, docs/src/vendor/react-over/compute-position/get-go-higher-from-rotated-coordinates.js, docs/src/vendor/react-over/compute-position/index.js, docs/src/vendor/react-over/compute-position/rotation.js, docs/src/vendor/react-over/compute-position/skip-boundary.js, docs/src/vendor/react-over/get-styles.js, docs/src/vendor/react-over/identification.js, docs/src/vendor/react-over/index.js, docs/src/vendor/react-over/is-valid-trigger-element.js, docs/src/vendor/react-over/over-wrapper.js, docs/src/vendor/react-over/overlay.js, docs/src/vendor/react-over/simple-shallow-equals.js, docs/src/vendor/react-over/validate-over-config.js, docs/src/vendor/react-over/warning.js
As part of #109 
---
react-over is copypasta'd into the vendor directory for now
=> Show import statement in catalog on click

docs/readmes/icons.md, docs/src/components/buttons.js, docs/src/components/chips.js, docs/src/components/component-doc.css, docs/src/components/progress-indicators.js, docs/src/components/selection-controls.js, docs/src/components/text-fields.js, docs/src/icons/index.js
=> Use table on component directory pages

docs/components.js, docs/examples/text-area.js, docs/readmes/field.md, docs/readmes/text-area.md, docs/src/components/text-fields.js, docs/static.config.js, src/field/field.css, src/field/field.js, src/index.js, src/input/input.css, src/text-area/text-area.js, stories/text-area.stories.js
=> Add TextArea

src/avatar/avatar.css
This preserves image aspect ratio
=> Update avatar image CSS to only set height:100%

src/expandable/expandable.js
=> Add callbacks to Expandable

docs/components.js, docs/examples/navigation.js, docs/readmes/navigation.md, docs/static.config.js, src/index.js, src/navigation/navigation.css, src/navigation/navigation.js, stories/navigation.stories.js
=> Navigation

docs/readmes/navigation.md, src/navigation/navigation.js, stories/navigation.stories.js
=> Add ripple as a prop to Navigation

src/avatar/avatar.css, src/avatar/avatar.js
This ensures that non-square avatars are centered
---
Resolves #218
=> Use background for avatar image

docs/package.json, docs/src/home/index.md, docs/src/icons/catalog.css, docs/src/icons/catalog.js
As part of #109 
Todo:
1. Add success msg
2. Update visual design
=> Add copy import statement button

docs/src/common/footer.css, docs/src/common/header.css, docs/src/common/nav.css, docs/src/icons/catalog.css, docs/src/index.js, package.json
=> Add focus-visible polyfill

docs/package.json, docs/src/icons/catalog.css, docs/src/icons/catalog.js
=> Add clear button to search input

src/ripple/ripple.css
=> Update ripple size

build/generate-icons.js, package.json
=> Ensure the git clone of the icons repository is a specific SHA

docs/readmes/action-chip.md, docs/readmes/choice-chip.md, docs/readmes/filter-chip.md, docs/readmes/input-chip.md, src/action-chip/chip.css
=> Increase chip contrast

src/navigation/navigation.js
=> Remove href from button

.prettierignore, docs/components.js, docs/examples/action-chip.js, docs/examples/choice-chip.js, docs/examples/filter-chip.js, docs/examples/input-chip.js, docs/readmes/action-chip.md, docs/readmes/choice-chip.md, src/action-chip/action-chip.js, src/action-chip/chip.css, src/choice-chip/choice-chip.js
=> Update Chips CSS; update InputChip examples

src/expandable/expandable.js
I may reintroduce this after the results of #272
=> Fix Expandable ref

src/expandable/expandable.js
This must have been some leftover code from when I was trying to make this thing queue, but it doesn't seem to be necessary.
Atm it's just not queuing, so removing this code doesn't change the current behavior.
=> Remove placeholder queue of Expandable

docs/examples/input.js, docs/readmes/input.md, docs/src/components/text-fields.css, docs/src/components/text-fields.js, docs/src/icons/catalog.css, docs/src/icons/catalog.js, src/field/field.css, src/input/input.css, src/input/input.js, stories/input.stories.js
=> Add clearable and icon props to input

src/input/input.js
I'm testing the waters here for #272 .
Plan: do a prerelease, pull it into an app, try it out. If it goes well, I'll add this to the rest of Materialish and do a stable release.
=> Support ref internally and externally for input

build/generate-icons.js, src/navigation/navigation.css
=> Update sizing of icons

CHANGELOG.md, build/generate-icons.js, docs/readmes/input.md, docs/readmes/navigation.md, docs/readmes/table.md, package.json, src/input/input.js, src/navigation/navigation.css, src/navigation/navigation.js, src/table/table.js, src/utils/warning.js
WIP: testing out this release with some beta releases before cutting a stable.
Todo:
=> 0.17.0-beta

docs/src/components/component-doc.css, docs/src/components/component-doc.js, docs/src/icons/usage.js, docs/src/vendor/doc-components/code-manager/code-manager.js, docs/src/vendor/doc-components/editor/editor.js, docs/src/vendor/doc-components/preview/preview.js
This isn't my proudest work, from the perspective of code, but I'd rather get this out there, and then polish this up. tl;dr, the CodeManager stuff needs to be completely refactored at this point.
=> Show errors in docs

docs/src/icons/catalog.js
=> Fix clear icon on Catalog page
